import type { CampusTemplate } from "./types";

export const unpamTemplate: CampusTemplate = {
  id: "unpam",
  nama: "Universitas Pamulang",
  namaFakultas: "Fakultas Ekonomi dan Bisnis",
  programStudi: "Manajemen",
  logo: "/logo-unpam.png",
  primaryColor: "#0A3D91",
  secondaryColor: "#F4C400",
  font: "Times New Roman",
  fontSize: 12,
  lineSpacingMultiple: 1.5,
  marginCm: { top: 3, right: 3, bottom: 3, left: 4 },
  paragraphIndentCm: 1.25,
  headingBabFormat: "BAB {ROM}",
  headingSubbabFormat: "{NUM}.{SUB}",
  nomorBab: "romawi",
  nomorTabel: "arab",
  nomorGambar: "arab",
  captionTabelPosition: "atas",
  captionGambarPosition: "bawah",
  captionTabelFormat: "Tabel {BAB}.{NUM}",
  captionGambarFormat: "Gambar {BAB}.{NUM}",
  spacingBeforeHeadingPt: 12,
  spacingAfterHeadingPt: 6,
  halamanAwal: "romawi",
  halamanIsi: "arab",
  daftarPustakaGaya: "APA7",
  sitasiGaya: "APA",
};
