import type { CampusTemplate } from "./types";

export const unpamTemplate: CampusTemplate = {
  id: "unpam",
  pedomanTahun: 2021,
  pedomanNama: "Pedoman Tugas Akhir FEB UNPAM 2021",
  nama: "Universitas Pamulang",
  namaFakultas: "Fakultas Ekonomi dan Bisnis",
  programStudi: "Manajemen",
  logo: "/logo-unpam.png",
  primaryColor: "#0A3D91",
  secondaryColor: "#F4C400",
  font: "Times New Roman",
  fontSize: 12,
  lineSpacingMultiple: 2,
  marginCm: { top: 4, right: 3, bottom: 3, left: 4 },
  paragraphIndentCm: 1.5,
  headingBabFormat: "BAB {ROM}",
  headingSubbabFormat: "{NUM}.{SUB}",
  nomorBab: "romawi",
  nomorTabel: "arab",
  nomorGambar: "arab",
  captionTabelPosition: "atas",
  captionGambarPosition: "bawah",
  captionTabelFormat: "Tabel {BAB}.{NUM}",
  captionGambarFormat: "Gambar {BAB}.{NUM}",
  spacingBeforeHeadingPt: 0,
  spacingAfterHeadingPt: 0,
  halamanAwal: "romawi",
  halamanIsi: "arab",
  daftarPustakaGaya: "APA-FEB2021",
  sitasiGaya: "APA",
};
